config/routes.rb
Agileway::Application.routes.draw do
root :to => "tasklists#index"
 resource :session
 resource :accounts

 resources :users, :controller => 'accounts'

  resources :tasks do
  post 'nextaction', :on => :collection
end
   
 
 resources :tasklists do
  resources :tasks
  
end
 resources :tasklists do
resources :tasks do
  member do
    put 'complete'
	put 'uncomplete'
   end
  end
end 

   match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"
match 'register', :to => 'sessions#register', :as => "register"

end

app/models/tasklist.rb
class Tasklist < ActiveRecord::Base
 has_many :tasks,  :conditions => "status != 'C'"
 
 has_many :todo_tasks, :class_name => "Task",
    :conditions => "next_action == true"
 
 has_many :completed_task, :class_name => "Task",
    :conditions => "status = 'C'"
 
 

end

app/controllers/tasklists_controller.rb
class TasklistsController < ApplicationController
 before_filter :authenticate
# GET /tasks
  # GET /tasks.json
  def index
  
  @tasklists =  Tasklist.where("user_id = ?", session[:user_id])
  @todo_tasks = Task.where("next_action = ? and user_id = ? ", true,session[:user_id] )
  
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasklists }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @tasklist = Tasklist.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tasklists }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @tasklist = Tasklist.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tasklists }
    end
  end

  # GET /tasks/1/edit
  def edit
  
    @tasklist = Tasklist.find(params[:tasklist_id])
	
  end

  # POST /tasks
  # POST /tasks.json
  def create
  
  @tasklist = current_user.tasklists.new(params[:tasklist]);
 
    respond_to do |format|
      if @tasklist.save
        format.html { redirect_to @tasklist, notice: 'Tasklist was successfully created.' }
        format.json { render json: @tasklist, status: :created, location: @tasklist }
      else
        format.html { render action: "new" }
        format.json { render json: @tasklist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @tasklist = current_user.tasklists.find(params[:id])

    respond_to do |format|
      if @tasklist.update_attributes(params[:tasklist])
        format.html { redirect_to @tasklist, notice: 'Tasklist was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @tasklist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
  
    @tasklist = current_user.tasklists.find(params[:id])
    @tasklist.destroy

    respond_to do |format|
      format.html { redirect_to @tasklist }
      format.json { head :ok }
    end
  end
end

app/helpers/tasklists_helper.rb
module TasklistsHelper
end

app/views/tasklists/_form.html.erb
<%= form_for(@tasklist) do |f| %>
  <% if @tasklist.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@tasklist.errors.count, "error") %> prohibited this tasklist from being saved:</h2>
    <ul>
    <% @tasklist.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
 
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasklists/create.js.erb
$('#tasks').append("<%= escape_javascript(render(@task)) %>");
$('#new_task')[0].reset();
alert('hi');

app/views/tasklists/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasklists/index.html.erb
<div class="span-24">

<br><br>
<h1>My Lists</h1>
<div class="span-16">


 
<% @todo_tasks.each do |task| %>

  

<h3>
  <%= task.title %>
 </h3>
 <%= check_box_tag 'next_action', task.id, task.next_action, :class => 'next_action' %> 
    

<hr class ="space">
<% end %>
</div>







<div class="span-8 last">
  <h3>My Task Lists</h3>
  <hr>
<% @tasklists.each do |tasklist| %>

  
<div class="span-3">
<%= link_to tasklist.title, tasklist %>
    
</div>	
<div class ="span-2">
<%= link_to image_tag("/assets/edit_active.png", :border=>0), edit_tasklist_path(tasklist) %>
</div>

<div class = "span-2">
	<%= link_to image_tag("/assets/delete_active.png", :border=>0), tasklist, confirm: 'Are you sure?', method: :delete %>
</div>
<hr class ="space">
<% end %>
</div>

<br />
<br />
<hr/>
<%= link_to 'New Task List', new_tasklist_path %>

app/views/tasklists/new.html.erb
<h1>New Tasklist</h1>

<%= render 'form' %>



<%= link_to 'Back', tasklists_path %>

app/views/tasklists/show.html.erb
<div class="span-16  ">




<p>
  
  <h2>
  <%= @tasklist.title  %>
  <h2>
</p>


<h3>Current Tasks </h3>
   
<div id="tasks">
<%= render :partial => "tasks/show", 
           :collection => @tasklist.tasks,:locals => { :status => 'A' }, :as => :task  %>

</div>
<% if(!@tasklist.completed_task.empty?)

%>
<h3>Completed task </h3>
   
<div id="completedtask">
<%= render :partial => "tasks/show", 
           :collection => @tasklist.completed_task, :locals => { :status => 'C' }, :as => :task  %>

</div>		   
	<% 

end if
%>

<h3>Add new Task</h3>	

<%= render "tasks/form" %>
<%= link_to 'Back', tasklist_path %>
</div>
<div class="span-8 last">

</div>