config/routes.rb
Agileway::Application.routes.draw do
root :to => "tasklists#index"
 resource :session
 resource :accounts

 resources :users, :controller => 'accounts'

  resources :tasks do
  post 'nextaction', :on => :collection
end
   
 
 resources :tasklists do
  resources :tasks
  
end
 resources :tasklists do
resources :tasks do
  member do
    put 'complete'
	put 'uncomplete'
   end
  end
end 

   match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"
match 'register', :to => 'sessions#register', :as => "register"

end

app/models/task.rb
class Task < ActiveRecord::Base
 validates :title, :presence => true
  belongs_to :tasklist

 end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_filter :load_tasklist, :except => [:destroy, :complete,:nextaction]
  before_filter :authenticate
  # GET /tasks
  # GET /tasks.json
  def index
  
  @tasks =  Task.where("user_id = ?", session[:user_id])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
	
  end

  
  
  # POST /tasks
  # POST /tasks.json
  def create
  
  
   @task = @tasklist.tasks.create(params[:task]);
    
	@task.user_id = session[:user_id];
	
 @task.status='A';
      if @task.save
		 respond_to do |format|
        #format.html { redirect_to @tasklist, notice: 'Task was successfully created.' }
		format.js
		 end
      else
	   respond_to do |format|
        format.html { render action: "new" }
        format.js 
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to @tasklist, notice: 'Task was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
  
    @tasklist = current_user.tasklists.find(params[:tasklist_id])
    @task = @tasklist.tasks.find(params[:id])
    
    @task.destroy

    respond_to do |format|
	format.html { redirect_to @tasklist, notice: 'Task was successfully deleted.' }
      
      format.json { head :ok }
    end
  end
  
  
  
  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def complete 
   
	@tasklist = current_user.tasklists.find(params[:tasklist_id])
    @task = @tasklist.tasks.find(params[:id])
    
    @task.status="C"
	 
    if @task.update_attributes(params[:task])
		 respond_to do |format|     
		format.html
			 format.js
		end
      else
       format.html { redirect_to tasklist_url }
        format.js
      end
  end
  
  
    # DELETE /tasks/1
  # DELETE /tasks/1.json
  def uncomplete 
   
	@tasklist = current_user.tasklists.find(params[:tasklist_id])
    @task = @tasklist.completed_task.find(params[:id])
    
    @task.status="A"
	 
    if @task.update_attributes(params[:task])
		 respond_to do |format|     
		format.html
			 format.js
		end
      else
       format.html { redirect_to tasklist_url }
        format.js
      end
  end
  
  
      # DELETE /tasks/1
  # DELETE /tasks/1.json
  def nextaction 
   

    @task = Task.find(params[:id])
	 
      @task.next_action=  !@task.next_action

	@task.save
  
		render :nothing => true	
	   
	 
  end
  
  
  
  private
    def load_tasklist
      @tasklist = Tasklist.find(params[:tasklist_id])
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for([@tasklist, @tasklist.tasks.new], :remote => true) do |f| %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/_show.html.erb
<%= div_for task do %>
<div class="span-20  ">

<div class ="span-10 ">
<div class ="span-2">
<% 

if( status != nil && status  =='C')
    css_display ="text-decoration:line-through;"
	else
	css_display =""
	end
%>
<% if(status != nil && status  =='C') %>

  <%= link_to "Undo complete", uncomplete_tasklist_task_path(task.tasklist,task), :method => :put , :remote => true  %>
  <% else %>
  <%= link_to "Mark as complete", complete_tasklist_task_path(task.tasklist,task), :method => :put , :remote => true %>
  
  <%
  end
	
%>

	  
</div>
<h3 style = <%= css_display %> >
  <%= task.title %>
 </h3>
</div>

<div class ="span-5">
<b>Next Action </b>

  <%= check_box_tag 'next_action', task.id, task.next_action, :class => 'next_action' %> 
</div>

<div class ="span-2">
<%= link_to image_tag("/assets/edit_active.png", :border=>0), edit_tasklist_task_path(task.tasklist,task)  %>
</div>

<div class = "span-2">
	<%= link_to image_tag("/assets/delete_active.png", :border=>0), [task.tasklist, task],
               :confirm => 'Are you sure?',
               :method => :delete %>
</div>
<hr class ="space">

</div>
<div class ="span-4 last">
</div>
<% end %>

app/views/tasks/complete.js.erb
$("#<%= dom_id(@task) %>").remove()
$('#completedtask').append("<%= escape_javascript(render :partial => "tasks/show", 
           :object => @task, :locals => { :status => 'C' }, :as => :task) %>");

app/views/tasks/create.js.erb
$('#tasks').append("<%= escape_javascript(render :partial => "tasks/show", :locals => { :status => 'A' }, :object => @task,:as => :task) %>");
$('#new_task')[0].reset();

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= form_for([@tasklist, @task],:html => { :method => :put }) do |f| %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>



<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Notes</th>
    <th>Effective at</th>
    <th>Duedate at</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  
<% @tasks.each do |task| %>
  <tr>
  
  
    
    <td><%= task.title %></td>
    <td><%= task.notes %></td>
    <td><%= task.effective_at %></td>
    <td><%= task.duedate_at %></td>
    <td><%= task.status %></td>
    <td><%= link_to 'Show', task %></td>
    <td><%= link_to 'Edit', edit_task_path(task) %></td>
    <td><%= link_to 'Destroy', task, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>


<%= render 'form' %>



<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @task.title %>
</p>

<p>
  <b>Notes:</b>
  <%= @task.notes %>
</p>

<p>
  <b>Effective at:</b>
  <%= @task.effective_at %>
</p>

<p>
  <b>Duedate at:</b>
  <%= @task.duedate_at %>
</p>

<p>
  <b>Status:</b>
  <%= @task.status %>
</p>


<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/uncomplete.js.erb
$("#<%= dom_id(@task) %>").remove()
$('#tasks').append("<%= escape_javascript(render :partial => "tasks/show", 
           :object => @task, :locals => { :status => 'A' }, :as => :task) %>");